version: '3'

tasks:
  build:frontend:
    dir: frontend
    cmds:
      - npm ci
      - npm run build
  build:server:
    deps:
      - task: build:frontend
    dir: server
    cmds:
      - cp -r ../frontend/dist pkg/public
      - go build -tags embed -o web cmd/main.go
      - rm -rf pkg/public/dist
      - mv web ../web
